In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.3'

In [3]:
list1 = [1,4,5,6,7]

In [6]:
a = np.array(list1)
a

array([1, 4, 5, 6, 7])

In [7]:
a.shape

(5,)

In [8]:
a.dtype

dtype('int64')

In [9]:
arr1 = np.array([3,3,4,5,6,6,7])
arr1.ndim

1

In [10]:
arr2 = np.array([[1,2,3,5],[4,5,4,3]])
arr2.ndim

2

In [11]:
arr2

array([[1, 2, 3, 5],
       [4, 5, 4, 3]])

In [12]:
arr3 = np.array([[[1,2],[3,5],[[4,5],[4,3]]]])
arr3.ndim

/tmp/ipykernel_4925/2168924567.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 = np.array([[[1,2],[3,5],[[4,5],[4,3]]]])


3

In [13]:
arr3

array([[[1, 2],
        [3, 5],
        [list([4, 5]), list([4, 3])]]], dtype=object)

In [14]:
arr3 = np.array([[[1,2],[3,5]],[[[4,5],[4,3]]]])
arr3.ndim

/tmp/ipykernel_4925/934044101.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 = np.array([[[1,2],[3,5]],[[[4,5],[4,3]]]])


1

In [15]:
arr3 = np.array([[[1,2],[3,5]],[[4,5],[4,3]]])
arr3.ndim

3

In [16]:
arr3

array([[[1, 2],
        [3, 5]],

       [[4, 5],
        [4, 3]]])

In [19]:
arr1

array([3, 3, 4, 5, 6, 6, 7])

In [20]:
arr1[1]

3

In [22]:
arr1[2] + arr1[4]

10

In [23]:
arr2

array([[1, 2, 3, 5],
       [4, 5, 4, 3]])

In [24]:
arr2[0,2]

3

In [25]:
arr2[1,3]

3

In [26]:
arr2

array([[1, 2, 3, 5],
       [4, 5, 4, 3]])

In [28]:
arr2[1,1:4]

array([5, 4, 3])

In [29]:
arr2.shape

(2, 4)

In [31]:
arr = np.array([1,2,3,4,5,6,7,8])
arr.shape

(8,)

In [33]:
arr_n = arr.reshape(2,4)
arr_n.shape

(2, 4)

In [34]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.shape

(9,)

In [36]:
arr_n = arr.reshape(3,3)
arr_n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr_n.shape

(3, 3)

In [38]:
arr_n.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr_n.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr_n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9


In [44]:
arr2

array([[1, 2, 3, 5],
       [4, 5, 4, 3]])

In [46]:
for i in arr2:
    for j in i:
        print(j)

1
2
3
5
4
5
4
3


In [47]:
for i in np.nditer(arr2):
    print(i)

1
2
3
5
4
5
4
3


In [50]:
for idx,x in np.ndenumerate(arr2):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 5
(1, 0) 4
(1, 1) 5
(1, 2) 4
(1, 3) 3


In [51]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr = np.array([8,7,65,4,6])
arr

array([ 8,  7, 65,  4,  6])

In [53]:
np.sort(arr)

array([ 4,  6,  7,  8, 65])

In [56]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
x = np.random.randint(10)
x

5

In [63]:
x = np.random.randint(low=2, high=50, size=80)
x

array([ 8,  4, 14, 35, 24, 15, 47, 10,  4,  2,  8,  4, 12, 38, 32, 32, 31,
        2,  2, 29,  6,  3, 24, 30, 22, 26,  3, 13, 49, 43,  9, 42, 43, 27,
       18, 13, 47, 15, 30, 12, 43,  3, 12, 18, 33,  5, 13,  3, 23,  3, 44,
       43, 10, 42, 10, 22, 18, 34, 41, 14,  3, 10, 33, 35, 49, 12, 24, 17,
       39, 12, 45,  5, 18,  4, 34, 27, 34, 35, 35, 35])

In [67]:
x = np.random.rand(5)
x

array([0.79675763, 0.98041783, 0.0485732 , 0.28770093, 0.33759899])

In [70]:
a1 = np.array([4,5,6,7])
a2 = np.array([10,5,2,1])
a1,a2

(array([4, 5, 6, 7]), array([10,  5,  2,  1]))

In [71]:
np.minimum(a1,a2)

array([4, 5, 2, 1])

In [72]:
np.maximum(a1,a2)

array([10,  5,  6,  7])

In [73]:
np.min(a1)

4

In [74]:
np.max(a1)

7

In [75]:
np.sum(a1)

22